In [3]:
#Load the dataset

import pandas as pd 

dataset = pd.read_csv('hate_speech.csv') 

dataset.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [11]:
dataset.shape

(5242, 3)

In [13]:
dataset.label.value_counts()

label
0    3000
1    2242
Name: count, dtype: int64

In [15]:
for index, tweet in enumerate(dataset["tweet"][10:15]):

    print(index+1,"-",tweet)

1 -  ↝ #ireland consumer price index (mom) climbed from previous 0.2% to 0.5% in may   #blog #silver #gold #forex
2 - we are so selfish. #orlando #standwithorlando #pulseshooting #orlandoshooting #biggerproblems #selfish #heabreaking   #values #love #
3 - i get to see my daddy today!!   #80days #gettingfed
4 - ouch...junior is angry😐#got7 #junior #yugyoem   #omg 
5 - i am thankful for having a paner. #thankful #positive     


In [17]:
import re

#Clean text from noise

def clean_text(text):

    #Filter to allow only alphabets

    text = re.sub(r'[^a-zA-Z\']', ' ', text)

    #Remove Unicode characters

    text = re.sub(r'[^\x00-\x7F]+', ' ', text)

    #Convert to lowercase to maintain consistency

    text = text.lower()  

    return text

In [19]:
dataset['clean_text'] = dataset.tweet.apply(lambda x: clean_text(x))

In [21]:
dataset.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                          clean_text  
0    user when a father is dysfunctional and is s...  
1   user  user thanks for  lyft credit i can't us...  
2                                bihday your majesty  
3   model   i love u take with u all the time in ...  
4             factsguide  society now     motivation  
5        huge fan fare and big talking before the...  
6    user camping tomorrow  user  user  user  use...  
7  the next school year is the year for exams    ...  
8  we won    love the land     allin  cavs  champ...  
9    user  user welcome here    i'm   it's so  gr...

In [23]:
from nltk.corpus import stopwords

# listing stop words

len(stopwords.words('english'))

179

In [24]:
stop = stopwords.words('english')

In [25]:
#Generate word frequency

def gen_freq(text):

    #Will store the list of words

    word_list = []

    #Loop over all the tweets and extract words into word_list

    for tw_words in text.split():

        word_list.extend(tw_words)

    #Create word frequencies using word_list

    word_freq = pd.Series(word_list).value_counts()

    #Drop the stopwords during the frequency calculation

    word_freq = word_freq.drop(stop, errors='ignore')

    return word_freq

In [26]:
#Check whether a negation term is present in the text

def any_neg(words):

    for word in words:

        if word in ['n', 'no', 'non', 'not'] or re.search(r"\wn't", word):

            return 1

        else:

            return 0

In [27]:
#Check whether one of the 100 rare words is present in the text

def any_rare(words, rare_100):

    for word in words:

        if word in rare_100:

            return 1

        else:

            return 0

In [28]:
#Check whether prompt words are present

def is_question(words):

    for word in words:

        if word in ['when', 'what', 'how', 'why', 'who', 'where']:

            return 1

        else:

            return 0

In [29]:
word_freq = gen_freq(dataset.clean_text.str)

#100 most rare words in the dataset

rare_100 = word_freq[-100:] # last 100 rows/words

#Number of words in a tweet

dataset['word_count'] = dataset.clean_text.str.split().apply(lambda x: len(x))

#Negation present or not

dataset['any_neg'] = dataset.clean_text.str.split().apply(lambda x: any_neg(x))

#Prompt present or not

dataset['is_question'] = dataset.clean_text.str.split().apply(lambda x: is_question(x))

#Any of the most 100 rare words present or not

dataset['any_rare'] = dataset.clean_text.str.split().apply(lambda x: any_rare(x, rare_100))

#Character count of the tweet

dataset['char_count'] = dataset.clean_text.apply(lambda x: len(x))

In [30]:
dataset.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                          clean_text  word_count  any_neg  \
0    user when a father is dysfunctional and is s...          18        0   
1   user  user thanks for  lyft credit i can't us...          19        0   
2                                bihday your majesty           3        0   
3   model   i love u take with u all the time in ...          12        0   
4             factsguide  society now     motivation           4        0   
5        huge fan fare and big talking before the...          18        0   
6    user camping tomorrow  user  user  user  use...          11        0   
7  the next school year is the year for exams    ...          20        0   
8  we won    love the land     allin  cavs  champ...          10        0   
9    user  user welcome here    i'm   it's so  gr...           8        0   

   is_question  any_rare  char_count  
0            0         0         102  
1            0         0         122  
2            0         0          21  
3            0         0          86  
4            0         0          39  
5            0         0         116  
6            0         0          74  
7            0         0         143  
8            0         0          87  
9            0         0          50

In [39]:
from sklearn.model_selection import train_test_split
X = dataset[['word_count', 'any_neg', 'any_rare', 'char_count', 'is_question']]
y = dataset.label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
                                                    random_state=0)

In [41]:
from sklearn.naive_bayes import GaussianNB

 

#Initialize GaussianNB classifier

model = GaussianNB()

#Fit the model on the train dataset

model = model.fit(X_train, y_train)

#Make predictions on the test dataset

pred = model.predict(X_test)

In [43]:
model.predict(X_test[5:10])

array([0, 1, 1, 1, 1])

In [45]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, pred)*100, "%")

Accuracy: 42.99332697807436 %


In [47]:
from sklearn.ensemble import RandomForestClassifier

#Create a random forest classifier, 100 trees

clf_rf=RandomForestClassifier()

 

#Train the model using the training sets

clf_rf.fit(X_train,y_train)

 

rf_pred=clf_rf.predict(X_test).astype(int)

In [48]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,rf_pred))  

print(classification_report(y_test,rf_pred))  

print("Accuracy:",accuracy_score(y_test, rf_pred))

[[399 200]
 [234 216]]
              precision    recall  f1-score   support

           0       0.63      0.67      0.65       599
           1       0.52      0.48      0.50       450

    accuracy                           0.59      1049
   macro avg       0.57      0.57      0.57      1049
weighted avg       0.58      0.59      0.58      1049

Accuracy: 0.5862726406101049


In [51]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(class_weight='balanced') 

logreg.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [53]:
y_pred = logreg.predict(X_test) #predicting the values

In [58]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.63      0.58      0.61       599
           1       0.49      0.54      0.52       450

    accuracy                           0.57      1049
   macro avg       0.56      0.56      0.56      1049
weighted avg       0.57      0.57      0.57      1049



In [60]:
Text = "I am learning NLP"

In [62]:
 # Importing the library

import pandas as pd

# Generating the features

pd.get_dummies(Text.split())

I    NLP     am  learning
0   True  False  False     False
1  False  False   True     False
2  False  False  False      True
3  False   True  False     False

In [64]:
text = ["i love NLP and i will learn NLP in 2month"]

# single characters are ignored by count vectorizer

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

 

vectorizer = CountVectorizer()

vectorizer.fit(text)

vector = vectorizer.transform(text)

In [68]:
print(vectorizer.vocabulary_)

print(vector.toarray())

{'love': 4, 'nlp': 5, 'and': 1, 'will': 6, 'learn': 3, 'in': 2, '2month': 0}
[[1 1 1 1 1 2 1]]


In [70]:
CountVectorizer?

Init signature:
CountVectorizer(
    *,
    input='content',
    encoding='utf-8',
    decode_error='strict',
    strip_accents=None,
    lowercase=True,
    preprocessor=None,
    tokenizer=None,
    stop_words=None,
    token_pattern='(?u)\\b\\w\\w+\\b',
    ngram_range=(1, 1),
    analyzer='word',
    max_df=1.0,
    min_df=1,
    max_features=None,
    vocabulary=None,
    binary=False,
    dtype=<class 'numpy.int64'>,
)
Docstring:     
Convert a collection of text documents to a matrix of token counts.

This implementation produces a sparse representation of the counts using
scipy.sparse.csr_matrix.

If you do not provide an a-priori dictionary and you do not use an analyzer
that does some kind of feature selection then the number of features will
be equal to the vocabulary size found by analyzing the data.

For an efficiency comparison of the different feature extractors, see
:ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.

Read more in the :ref:`User Guide

In [72]:
print(vector)

  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	2
  (0, 6)	1


In [74]:
df = pd.DataFrame(data=vector.toarray(), columns=vectorizer.get_feature_names_out() )

df

2month  and  in  learn  love  nlp  will
0       1    1   1      1     1    2     1

In [76]:
text = 'I am learning NLP'

In [78]:
from textblob import TextBlob

#For unigram : Use n = 1

TextBlob(text).ngrams(1)

[WordList(['I']), WordList(['am']), WordList(['learning']), WordList(['NLP'])]

In [80]:
#For Bigram : For bigrams, use n = 2

TextBlob(text).ngrams(2)

[WordList(['I', 'am']),
 WordList(['am', 'learning']),
 WordList(['learning', 'NLP'])]

In [84]:
TextBlob(text).ngrams(3)

[WordList(['I', 'am', 'learning']), WordList(['am', 'learning', 'NLP'])]

In [86]:
TextBlob(text).ngrams(4)

[WordList(['I', 'am', 'learning', 'NLP'])]

In [88]:
Text = ["The quick brown fox jumped over the lazy dog.", "The dog.", "The fox"]

In [92]:
#Import TfidfVectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

#Create the transform

vectorizer = TfidfVectorizer()

#Tokenize and build vocab

vectorizer.fit(Text)

 

#Summarize

print(vectorizer.vocabulary_)

print(vectorizer.idf_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


In [94]:
#Import TfidfVectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

#Create the transform

vectorizer = TfidfVectorizer()

#Tokenize and build vocab

vectorizer.fit(Text)

 

#Summarize

print(vectorizer.vocabulary_)

print(vectorizer.idf_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]
